version: "3"

services:
  sonarqube:
    image: library/sonarqube:8.4.1-community
    expose:
      - 9000
    ports:
      - "127.0.0.1:9000:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/docker_sonar
      - SONARQUBE_JDBC_USERNAME=docker_sonar
      - SONARQUBE_JDBC_PASSWORD=docker_sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres:13-alpine
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=docker_sonar
      - POSTGRES_PASSWORD=docker_sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data


networks:
  sonarnet:

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
