version: '3'

services:
  app:
    image: app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/app
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:12
    env_file: .env
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:4.16
    env_file: .env
    ports:
      - 80:80
    depends_on:
      - db
